repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Run ruff linter
        entry: uv run ruff check --fix
        language: system
        types: [python]
        require_serial: false

      - id: ruff-format
        name: Run ruff formatter
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
